### ISSUE TITLE
Login pagina bugged

### ISSUE THREAD

**Issue by joeyb276** [BemaWegenbouw/Website#10]
De login pagina laad niet vanwege de php code, omdat deze eerder wordt uitgevoerd of zo.

PS je moet helemaal via localhost/staff/login.php naar de pagina. Kan dit niet via localhost/login  ( zonder .php)?

**Comment by Hevadejo** [comment]
Ik ben ermee bezig

**Comment by Hevadejo** [comment]
De inlogpagina heb ik enkele commits geleden helemaal afgemaakt.
